fbgemm_embedding:
  parser: embedding
  install_script: ./packages/fbgemm/install_embedding.sh
  cleanup_script: ./packages/fbgemm/cleanup_embedding.sh
  path: ./benchmarks/fbgemm_embedding/tbe_inference_benchmark
  metrics:
    - bandwidth

fbgemm_embedding_cpu_a:
  parser: fbgemm
  install_script: ./packages/fbgemm/install_embedding.sh
  cleanup_script: ./packages/fbgemm/cleanup_embedding.sh
  path: ./benchmarks/fbgemm_embedding/FP16Benchmark
  metrics:
    - bandwidth

fbgemm_embedding_cpu_b:
  parser: fbgemm
  install_script: ./packages/fbgemm/install_embedding.sh
  cleanup_script: ./packages/fbgemm/cleanup_embedding.sh
  path: ./benchmarks/fbgemm_embedding/EmbeddingSpMDM8BitBenchmark
  metrics:
    - bandwidth

rebatch:
  parser: rebatch
  install_script: ./packages/rebatch/install_rebatch.sh
  cleanup_script: ./packages/rebatch/cleanup_rebatch.sh
  path: ./benchmarks/rebatch/rebatchBench
  metrics:
    - bandwidth
    - time_per_batch_us

chm:
  parser: chm
  install_script: ./packages/chm/install_chm.sh
  cleanup_script: ./packages/chm/cleanup_chm.sh
  path: ./benchmarks/chm/chm_bench
  metrics:
    - Mops/sec

deser:
  parser: deser
  install_script: ./packages/deser/install_deser.sh
  cleanup_script: ./packages/deser/cleanup_deser.sh
  path: ./benchmarks/deser/deser_bench
  metrics:
    - Mops/sec

adsim:
  parser: adsim
  install_script: ./packages/adsim/install_adsim.sh
  cleanup_script: ./packages/adsim/cleanup_adsim.sh
  path: ./benchmarks/adsim/run_adsim.py
  roles:
    - client
    - server
  tags:
    scope:
      - app
      - ads
    component:
      - cpu
      - memory
  metrics:
    - final_achieved_qps
    - final_latency_msec
    - final_requested_qps
    - target_latency_msec
    - target_latency_percentile
